#!/bin/sh
#
# This is part 2 of the ppp-on script. It will perform the connection
# protocol for the desired connection.
#
#exec chat -v						\
#	TIMEOUT		3				\
#	ABORT		'\nBUSY\r'			\
#	ABORT		'\nNO ANSWER\r'			\
#	ABORT		'\nRINGING\r\n\r\nRINGING\r'	\
#	''		\rAT				\
#	''		AT^dkjf				\
#	''		\rAT=wer				\
#	'OK-+++\c-OK'	ATH0				\
#	TIMEOUT		30				\
#	OK		ATDT$TELEPHONE			\
#	CONNECT		''				\
#	ogin:--ogin:	$ACCOUNT			\
#	assword:	$PASSWORD

exec /usr/sbin/chat -v																					\
#exec /home/zhaoqt/scripts/chat -v						\																			\
TIMEOUT        15                              														\
""               "AT"                            \
"OK"             "ATH#777"                            \
