#!/bin/sh
if [ $# == 0 ] ; then
	mount -t nfs 10.2.6.100:/home/share /home -o nolock
	echo "mount -t nfs 10.2.6.100:/home/share /home -o nolock"

else 
	mount -t nfs 10.2.$1.100:/home/share /home -o nolock
	echo "mount -t nfs 10.2.$1.100:/home/share /home -o nolock"
fi
